name: All_collection_recovery

on:
  schedule:
    - cron: '25 2 * * *'   # ~8:00 AM IST
    - cron: '25 4 * * *'   # ~10:00 AM IST
    - cron: '25 6 * * *'   # ~12:00 PM IST
    - cron: '25 8 * * *'   # ~2:00 PM IST
    - cron: '25 10 * * *'  # ~4:00 PM IST
    - cron: '25 12 * * *'  # ~6:00 PM IST
    - cron: '25 14 * * *'  # ~8:00 PM IST

  workflow_dispatch:
    inputs:
      run_ossummary:
        description: 'Run OS Summary Collection?'
        required: false
        default: 'true'
      run_recovery:
        description: 'Run Recovery Update?'
        required: false
        default: 'true'
      run_cngos:
        description: 'Run CNG OS Collection?'
        required: false
        default: 'true'

jobs:
  run-All_collection_recovery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install gspread pandas google-auth

      - name: Run All_collection_recovery.py
        env:
          ACCOUNT_KEY_JSON: ${{ secrets.ACCOUNT_KEY_JSON }}
          RUN_OSSUMMARY: ${{ github.event.inputs.run_ossummary }}
          RUN_RECOVERY: ${{ github.event.inputs.run_recovery }}
          RUN_CNGOS: ${{ github.event.inputs.run_cngos }}
        run: |
          echo "ðŸš€ Running All_collection_recovery.py..."
          python All_collection_recovery.py
